### ISSUE TITLE
Unknown Identifier problem

### ISSUE THREAD

**Issue by Supershandy** [soomla/unity3d-profile#10]
Hi there,

i set up Soomla as stated in the Getting Started guide and have both the Core and Profile folders sitting in the plugins folder of my unity project.

As I write mostly in UnityScript, I initialised soomla in the Start() function of one of my scripts using SoomlaProfile.Initialize();

Problem is that Unity is throwing up an error code BCE0005 saying that "SoomlaProfile" is an unknown identifier., this is also a problem as well for the provider class.

**Comment by sluzky** [comment]
Hey @Supershandy,

Have you done `import Soomla.Profile`?

**Comment by Supershandy** [comment]
I had the thought last night about using import, rookie error haha, tried it this morning and it worked fine, thanks

**Comment by sluzky** [comment]
I deleted my comment before, but it was:

Have you done `import Soomla.Profile`?

Glad it helped.
