### ISSUE TITLE
How to build the java jars

### ISSUE THREAD

**Issue by mylemans** [soomla/unity3d-profile#11]
I'm having an extremely hard time getting the java sources to compile myself.

We want to patch in support for getting the access tokens (per provider), but step 1 is to get the code as it is now to compile, and I can't figure out how to do it.

Could you please advice (and maybe document) how to build on Windows?

If needed, instructions on how to do the same on Linux (from console), that is fine too.

**Comment by refaelos** [comment]
Which android project are you trying to build?

**Comment by mylemans** [comment]
All, but I succeeded at none :/

In general I'll have to patch the per-provider specific code and I assume also the 'common' library that exposes the 'interfaces' (will need to add a getAccessToken there too)

**Comment by refaelos** [comment]
Inside each one of the social providers [directories](https://github.com/soomla/android-profile/tree/master/social-providers) you'll find a script called `build_all`. Try running it and let me know.

**Comment by mylemans** [comment]
"package android.app does not exist"

**Comment by refaelos** [comment]
Maybe you don't have Android installed?
Can you provide some more informative logs and details?

Also, it'll be very useful for you to post your question on http://answers.soom.la
(this is where the SOOMLA community is)

**Comment by mylemans** [comment]
Done (see http://answers.soom.la/t/guide-on-how-to-build-the-java-jars-yourself/1836)

**Comment by refaelos** [comment]
cool. closing this one.
