### ISSUE TITLE
SOOMLA SoomlaProfile Provider not supported or not set as active: twitter

### ISSUE THREAD

**Issue by yehielliv** [soomla/unity3d-profile#12]
I've looked at all the posted issues here but all the options and suggestions did not solve this issue.
I have the twitter keys and secret fulfilled, the prefab are in place at well.
It does not show the login.
After 
SoomlaProfile.Login(Provider.TWITTER, null, null);
and
if (SoomlaProfile.IsLoggedIn(Provider.TWITTER))
fail.
Also for some reason the event is not fire correctly.
SoomlaProfile.Initialize();
ProfileEvents.OnSoomlaProfileInitialized += onSoomlaProfileInitialized;
But when I check onSoomlaProfileInitialized is does not get there.

What can be wrong.

Thanks

Elik

**Comment by refaelos** [comment]
@yehielliv you should ask your question on http://answers.soom.la. You'll get an answer much quicker.
