### ISSUE TITLE
 cannot sign in to twitter in Unity5.0

### ISSUE THREAD

**Issue by Mobinyaqoob** [soomla/unity3d-profile#14]
before  i posting this issue i read all the conversation of 
 cannot sign in to twitter #7 
but it not works in my case.
so i decide to post the issue here are my step i follow for making this app:
1.set contumer key and consumer secret.
2.drop both prefebs in hirarchy (core event )(profile event)
3.set soomla secret.
4.debug unity is chk.
5.permission in twitter is read and write.
6.callback url is set.
7.app name and twitter app name is same

For some how my unityRemote is not working i dont know why but i tried my best but it not work so
i m not able to send any log of it but i share my solution

and here is my code:

	public Provider targetProvider = Provider.TWITTER;
	public string message = "Hi Every One How Are You !";
	private Reward exampleReward = new BadgeReward ("example_reward", "Example Social Reward");
	// Use this for initialization
	void Start () {
		SoomlaProfile.Initialize();
	}
	
	// Update is called once per frame
	void Update () {
	
	}
	public void TwitterInitailize()
	{
		SoomlaProfile.Login (targetProvider,null,exampleReward);
		if (SoomlaProfile.IsLoggedIn (targetProvider)) {
			SoomlaProfile.UpdateStatus (targetProvider, message, null, exampleReward);
		} else
		{
			Debug.Log("Where is the error");
		}
	}

**Comment by refaelos** [comment]
please post this in http://answers.soom.la
You'll get a faster response there..
