### ISSUE TITLE
Facebook SDK 7.0.2 : `FB' does not contain a definition for `Logout'

### ISSUE THREAD

**Issue by leopripos** [soomla/unity3d-profile#30]
Assets/Plugins/Soomla/Profile/social-providers/FBSocialProvider.cs(55,28): error CS0117: `FB does not contain a definition for Logout`

Is soomla not ready support for Facebook SDK 7.0.2?
I found that `FB.Login` used in soomla but which avaliable in `facebook sdk 7.0.2` is `FB.LogInWithPublishPermissions and LogInWithReadPermissions`
Also with log out: in soomla `FB.Logout`, but fb sdk is `FB.LogOut`
I use `unity3d-profile v2.1.1`

Thanks..

**Comment by refaelos** [comment]
We don't support this version yet. It's a beta version.

**Comment by leopripos** [comment]
Hello rafaelos,
Thanks for the response

Owh, I see
May I get the beta version? For development :D
And where is it?

Thanks,

**Comment by refaelos** [comment]
Facebook's v7 is in beta ...

**Comment by leopripos** [comment]
Owh, I see
Sory"
:D
