### ISSUE TITLE
Facebook SDK 7.0.2 BETA, Unity 5.1.1f

### ISSUE THREAD

**Issue by 62316e** [soomla/unity3d-profile#38]
You cannot show two modal windows at once
UnityEngine.GUI:ModalWindow(Int32, Rect, WindowFunction, String)
EditorFacebookAccessToken:OnGUI() (at Assets/Facebook/Scripts/PlatformEditor/EditorFacebookAccessToken.cs:22)

ArgumentException: Getting control 0's position in a group with only 0 controls when doing Repaint
Aborting
UnityEngine.GUILayoutGroup.GetNext () (at C:/buildslave/unity/build/artifacts/generated/common/runtime/GUILayoutUtilityBindings.gen.cs:511)
UnityEngine.GUILayoutUtility.DoGetRect (Single minWidth, Single maxWidth, Single minHeight, Single maxHeight, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at C:/buildslave/unity/build/artifacts/generated/common/runtime/GUILayoutUtilityBindings.gen.cs:306)
UnityEngine.GUILayoutUtility.GetRect (Single width, Single height, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at C:/buildslave/unity/build/artifacts/generated/common/runtime/GUILayoutUtilityBindings.gen.cs:285)
UnityEngine.GUILayout.Space (Single pixels) (at C:/buildslave/unity/build/artifacts/generated/common/runtime/GUILayoutBindings.gen.cs:204)
EditorFacebookAccessToken.OnGUIDialog (Int32 windowId) (at Assets/Facebook/Scripts/PlatformEditor/EditorFacebookAccessToken.cs:28)
UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style) (at C:/buildslave/unity/build/artifacts/generated/common/runtime/GUIBindings.gen.cs:1458)

**Comment by refaelos** [comment]
We still don't support their beta version.
