### ISSUE TITLE
Twitter logging in with the same profile after logout

### ISSUE THREAD

**Issue by JamesDruid0806** [soomla/unity3d-profile#43]
Hi, there. I'm having a problem on the Twitter module on  this profile plugin. The logout mechanism seems to not completely logout the user. I mean after I log out, I try logging in again but what happens is that, the previous user is logged in again instead of showing the login form. Clearing the app's data seems to fix this (I'm using the plugin on an Android app by the way) but same thing, It will only show me the login form once, on the start, and after that, doing a log out and then a log in again will just log me in using the same account.

I already tried isolating the problem by creating a new project on unity with just your profile plugin, with twitter module only enabled and only coded the login and logout mechanism using two GUI buttons but same thing happens. I don't know if there's a proper undocumented way of logging out a twitter account with this plugin. I'll just provide the non-working code here:

```C#
using UnityEngine;
using System.Collections;
using Soomla.Profile;
public class Test : MonoBehaviour {

	// Use this for initialization
    void Start()
    {
        SoomlaProfile.Initialize();
        
    }
    
    public void TwitterSignout()
    {
        if (SoomlaProfile.IsLoggedIn(Provider.TWITTER))
        {
            SoomlaProfile.Logout(Provider.TWITTER);
          
        }
    }
    public void TwitterLogin()
    {
        if (SoomlaProfile.IsLoggedIn(Provider.TWITTER) == false)
        {
            SoomlaProfile.Login(Provider.TWITTER);
        }
    }
}

```

I also already tried playing around with the code like deleting the user's stored profile first before actually logging out and using the provided SoomlaProfileAndroid Class instead of the SoomlaProfile.

**Comment by refaelos** [comment]
@vedi can you take a look at this?

**Comment by EugeneButusov** [comment]
@JamesDruid0806 @refaelos, I think it solved there: https://github.com/soomla/android-profile/commit/4fb55946382516bcd735c79262e1ba2c373f5390

**Comment by refaelos** [comment]
@JamesDruid0806 we're closing this. Let us know if it happens again.
