### ISSUE TITLE
Is it possible to implement Google +1 button for Google Plus Social Platform?

### ISSUE THREAD

**Issue by timmy2702** [soomla/unity3d-profile#45]
Hi guys,

The plugin has been working great. I'm just wondering whether there is a feature for +1 button or not. It seems like there is no +1 button plugin available right now for Unity. It'd be great if you guys can support it or plan on that.

Thanks

**Comment by refaelos** [comment]
Can you post it to http://answers.soom.la ?

**Comment by timmy2702** [comment]
@refaelos submitted to the forum as ur request

**Comment by refaelos** [comment]
:+1:
