### ISSUE TITLE
Twitter login failed: 401:Authentication credentials

### ISSUE THREAD

**Issue by paynechu** [soomla/unity3d-profile#47]
Unity 5.1.3
Android SDK 6.0
Soomla
  Core Version 1.0.10
  Highway Version 2.0.0
  LevelUp Version 1.0.16
  Profile Version 2.1.5
  Store Version 1.8.3

After I call the `SoomlaProfile.Login(Provider.TWITTER);`. The FPS will drop to almost zero and will return Login failed: 401. I even tried to recreate a new project. But still got same error. I sure my credentials is correct. And also check and uncheck already after key in the `Consumer Key` and `Consumer Secret`. I have no clue what's the problem. Anyone can help ?

I/Unity   (13001): OnLoginFailed provider=twitter message=Login failed: 401:Authentication credentials (https://dev.twitter.com/pages/auth) were missing or incorrect. Ensure that you have set valid      consumer key/secret, access token/secret, and the system clock is in sync.

**Comment by refaelos** [comment]
you'll get a faster answer if sending this on http://answers.soom.la. Also, try to search for a solution there before asking.
