### ISSUE TITLE
Support for Facebook SDK 7.1.0

### ISSUE THREAD

**Issue by RabieZahid** [soomla/unity3d-profile#51]
When will Soomla Profile be updated to work for the new Facebook SDK, which works well on Unity and hopefully has a working post processing?

**Comment by refaelos** [comment]
@vedi are we supporting that?

**Comment by vedi** [comment]
@refaelos, the last FB SDK does not support Unity3d v4. We need to think how to solve this.

**Comment by RabieZahid** [comment]
Then again, FB's new SDK doesn't support Unity3d v4 anymore and anyone using the old SDK on 5.0 can't run post processing. So, why not update Soomla Profile for the new SDK (Unity 5.0 only) and if anyone running older Unity version and older Facebook SDK can simply use an older Soomla Profile plugin.

**Comment by refaelos** [comment]
@RabieZahid I think Profile is updated to the new SDK.

@vedi can you confirm?

**Comment by RabieZahid** [comment]
Could I get a link to the new version cause I don't see any updates on the repo or the packages provided on the website. 

The latest Facebook SDK has replaced FBResult with IResult class and they made some changes with the login, logout functions. Plus I also believe they got rid of the old post processing code, there is no third-party folder with the pbxparser and the pbxfix stuff in the latest SDK. I do not see these changes anywhere, highly doubt it's been updated.

**Comment by rsodre** [comment]
I tried to upgrade to FB SDK 71 and had to go back to 6.2.2.
Had a lot of problems, like no more FBResult, replaced by IResult.
Full changes here: https://developers.facebook.com/docs/unity/change-log#v7_1_0

**Comment by EugeneButusov** [comment]
@vedi @refaelos, `tjenkins` wrote at `SOOMLA Answers` the reason why FB SDK v7 isn't compatible yet with SOOMLA Profile yet. Details here: http://answers.soom.la/t/fbresult-could-not-be-found/3635/2

**Comment by EugeneButusov** [comment]
@refaelos @borisspektor, FB SDK v7 is supported now by SOOMLA Unity3D Profile. I think this issue is solved.

**Comment by refaelos** [comment]
@EugeneButusov great!!
