### ISSUE TITLE
xcode error for google+

### ISSUE THREAD

**Issue by robinDesBits** [soomla/unity3d-profile#6]
Hello ! 
we added google plus with soomla profile, and we have some errors on xcode:

Undefined symbols for architecture armv7:
"_kGTLPlusCollectionVisible", referenced from:
-[SoomlaGooglePlus getContacts:fail:] in libSoomlaiOSProfileGoogle.a(SoomlaGooglePlus.o)
"_kGTLAuthScopePlusUserinfoProfile", referenced from:
-[SoomlaGooglePlus startGooglePlusAuth] in libSoomlaiOSProfileGoogle.a(SoomlaGooglePlus.o)
"_OBJC_CLASS_$_GTLQueryPlus", referenced from:
objc-class-ref in libSoomlaiOSProfileGoogle.a(SoomlaGooglePlus.o)
"_kGTLAuthScopePlusLogin", referenced from:
-[SoomlaGooglePlus startGooglePlusAuth] in libSoomlaiOSProfileGoogle.a(SoomlaGooglePlus.o)
"_OBJC_CLASS_$_GTLServicePlus", referenced from:
objc-class-ref in libSoomlaiOSProfileGoogle.a(SoomlaGooglePlus.o)
"_OBJC_CLASS_$_GPPShare", referenced from:
objc-class-ref in libSoomlaiOSProfileGoogle.a(SoomlaGooglePlus.o)
"_OBJC_CLASS_$_GPPURLHandler", referenced from:
objc-class-ref in libSoomlaiOSProfileGoogle.a(SoomlaGooglePlus.o)
"_OBJC_CLASS_$_GPPSignIn", referenced from:
objc-class-ref in libSoomlaiOSProfileGoogle.a(SoomlaGooglePlus.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

probably a framework which is missing, but I don't know which one ?
thx for your help :)

**Comment by sluzky** [comment]
@robinDesBits did this solve your issue? can we close this?

**Comment by sluzky** [comment]
@robinDesBits closing this, re-open if still relevant

**Comment by robinDesBits** [comment]
Sorry, late answer. We solved all our problems by removing google + and twitter. Just Facebook is working fine, maybe we will try again later, but for now we have submitted our app without it.

**Comment by yerko18** [comment]
This problem was solved? because I have the same problem, after upgrading xCode 8 SDK 1.7 this problem did not happen, I had to update the SDK because the previous version did not support the Bitcode of xCode

I use:
Unity v5.3.6
xCode v8.0
Soomla Core v1.0.12
Soomla Profile v2.1.7
OS X v10.11.6
Google Plus SDK 1.7.1


I followed the steps od Google plus ->  https://github.com/soomla/ios-profile#google-plus
