### ISSUE TITLE
Unity 5.3.0 compatibility issue

### ISSUE THREAD

**Issue by Whyser** [soomla/unity3d-profile#60]
It's a small issue but worth mentioning since this error prevents the compilation of scripts which prevents the Soomla menu from being visible in the Unity Editor.

`Assets/Plugins/Soomla/Profile/ModalDialog.cs(15,58): error CS0619: UnityEngine.EventSystems.TouchInputModule' is obsolete: TouchInputModule is no longer required as Touch input is now handled in StandaloneInputModule.'`

Also: Can someone take a look at my comment: https://github.com/soomla/unity3d-profile/issues/31#issuecomment-157380705

**Comment by refaelos** [comment]
@Whyser can you post this on http://answers.soom.la ?

**Comment by EugeneButusov** [comment]
@Whyser, please track issue status in SOOMLA Public Roadmap: https://trello.com/c/cGnHbYvS/154-fix-support-unity-5-3-0

**Comment by Whyser** [comment]
I've now posted this issue on http://answers.soom.la (http://answers.soom.la/t/soomla-profile-compatibility-issue-with-unity-5-3-0-f1/4189).

**Comment by EugeneButusov** [comment]
This issue was resolved in Soomla Unity3d Profile v2.4.0. I'm closing this topic, please feel free to create new one if you find any issues regarding this fix.
