### ISSUE TITLE
Assets/Examples/Scripts/SubMenus/AppLinks.cs(35,17): error CS0103: The name `Constants' does not exist in the current context

### ISSUE THREAD

**Issue by JeeJee** [soomla/unity3d-profile#64]
Hi Soomla devs! 

Following this guide:

"<h3><a id="user-content-facebook" class="anchor" href="#facebook" aria-hidden="true"><span class="octicon octicon-link"></span></a>Facebook</h3>
<ol>
<li><p>Go over the guidelines for downloading and importing the official Facebook SDK: <a href="https://developers.facebook.com/docs/unity/getting-started/canvas">https://developers.facebook.com/docs/unity/getting-started/canvas</a>    - You don't need to initialize FB. SoomlaProfile will initialize it for you.</p>

<blockquote>
<p><strong>NOTE:</strong> for unity 4.6, use FB Unity SDK v6.1.</p>
</blockquote></li>
<li><p>Create an empty folder named <code>Facebook</code> under <code>Assets/Plugins</code></p></li>
<li><p>Move the folder <code>Scripts</code> from <code>Assets/Facebook</code> to <code>Assets/Plugins/Facebook</code>  -  SOOMLA works from the Plugins folder so it'll be available to UnityScript devs. So you'll have to move Facebook in there as well.</p>

<blockquote>
<p>When working under Unity version &gt; 4.5.0 (targeting iOS) please follow these extra steps:</p>

<ol>
<li><p>Edit the file <code>Assets/Facebook/Editor/iOS/fixup.projmods</code></p></li>
<li><p>Under <code>headerpaths</code> change <code>Facebook/Scripts</code> to <code>Plugins/Facebook/Scripts</code></p></li>
</ol>
</blockquote></li>
</ol>"

throws the following error:

"Assets/Examples/Scripts/SubMenus/AppLinks.cs(35,17): error CS0103: The name `Constants' does not exist in the current context".

Unity 5.2.2
Facebook SDK 7.2.2
Core 1.2.2
Profile 2.3.0

Targeting Android at the moment.

Thanks!

**Comment by borisspektor** [comment]
HI @JeeJee! Please post your problem in answers.soom.la you'll get a faster answer there.

**Comment by Blinkq** [comment]
Hello, This error come from facebook, when Scripts moved, and Facebook doesnt know where it gone.
With this extra steps, you showing where scripts are
i Edit the file Assets/Facebook/Editor/iOS/fixup.projmods
ii Under headerpaths change Facebook/Scripts to Plugins/Facebook/Scripts

**Comment by JeeJee** [comment]
Hi

Thank you for your reply.
Apologies I replied so late.

I am targeting Android, not iOS, but I have tried the steps in the guide and still the same error.
Using the Facebook sdk is quite straightforward so I decided to only use the Soomla store plugin.

Thank you again for the support,

JeeJee

**Comment by EugeneButusov** [comment]
Hi @JeeJee, sorry for too late reply. If it is still actual - just remove folder with Facebook examples and all will work.
