### ISSUE TITLE
cannot sign in to twitter

### ISSUE THREAD

**Issue by DeepakPant** [soomla/unity3d-profile#7]
I am getting console log 
"SOOMLA SoomlaProfile Provider not supported or not set as active: twitter". Can you help me where did i do wrong ? 
OS : Android kitkat unity 4.6.1

**Comment by sluzky** [comment]
Hey @DeepakPant,

Have you selected Twitter from the Soomla Settings window?

**Comment by noblakit01** [comment]
Me too.I selected Twitter from the Soomla Settings and fill in "Consumer Key" and "Consumer Secret" carefully. But I can't sign in Twitter.

Os: Unity 4.6.1

**Comment by DeepakPant** [comment]
@sluzky , Yep I did. And strange thing I found is if I tried to updateStatus without login In whole app crash.

**Comment by sluzky** [comment]
@DeepakPant you can'y updateStatus without logging in.

Are you getting the Twitter login window at all?
Can you turn on the debug messages in the Soomla Settings and provide a log?

**Comment by DeepakPant** [comment]
@sluzky  Yes i know i cannot update status but that should not crash system at all even i just did for test purpose assuming if I update twitter status it might fall back to showing login panel.

Nope I am not getting Twitter login window at all.

E/Unity   (25141): SOOMLA SoomlaProfile Provider not supported or not set as active: twitter is the only useful log i am getting

**Comment by sluzky** [comment]
@DeepakPant yes you might be right on that, we'll check that one out.

Are you working in the editor? if not, then turning on "Debug Messages" in Soomla Settings should give you a lot of useful log, which are coming from the native implementation. So there should be a huge log in logcat.

If you are working inside the editor, then Twitter will not work, since the implementation is based on a native implementation.

Also, did you add the `ProfileEvents` prefab? did you call `SoomlaProfile.Initialize();`in the `Start` of your game?

**Comment by DeepakPant** [comment]
@sluzky Yes i have done all basic procedure, Facebook works like a piece of cake its only in twitter. Its Unity 4.6.1 Patch 2 , I am working on right now.

**Comment by sluzky** [comment]
@DeepakPant you have not replied to my other questions...

**Comment by DeepakPant** [comment]
@sluzky  sorry , i meant I am working on a real device , debug message is on , ProfileEvents prefab is included in hierarchy and soomlaprofile  is initialized in start as it supposed  to be .

**Comment by sluzky** [comment]
@DeepakPant if you are working on a real device, please share a full log from the start of the app until the point where it cannot login. You can use [pastebin](http://pastebin.com) to share

**Comment by DeepakPant** [comment]
@sluzky It seems there was problem in twitter initialization. Here's my unity log.
 [Pastebin](http://pastebin.com/bwXNCXvk)

It might be import failure issue

**Comment by sluzky** [comment]
@DeepakPant from the looks of it you are missing the `AndroidProfileTwitter.jar` file.
It should be in `Assets/Plugins/Android` after you tick the Twitter checkbox in Settings.
Is it there?

**Comment by DeepakPant** [comment]
@sluzky  Yes its there

**Comment by sluzky** [comment]
@DeepakPant maybe it's not taking the jar for some reason. is there an error in the build log in the editor when you build?

**Comment by DeepakPant** [comment]
hello @sluzky  I updated new versions of soomla and old error is no more but I am getting some login error [Pastebin](http://pastebin.com/eZAXD9Yz)

There is XML  error
<error>Desktop applications only support the oauth_callback value 'oob'</error>

**Comment by sluzky** [comment]
@DeepakPant glad that error is gone.

This looks like an error from Twitter.
Make sure you have the correct consumer key and secret setup.
Also in the Twitter application settings make sure you filled in the Callback URL.

Let me know if it worked out

**Comment by DeepakPant** [comment]
@sluzky  Yes callback url lead to the error, It worked , But I have some curiosity.
SoomlaProfile.UpdateStatus posts to twitter without responding to user and there is no success response, user is unaware of what is posted behalf of them. Should we do manually? because as far as I Know that might be violation of policy not giving user to control what they post.

**Comment by DeepakPant** [comment]
And shouldn't it use my device twitter account so signing in is easy, just user has to press authorize button without entering login credentials and login and then authorizing. This is my first time twitter integration using unity,

**Comment by sluzky** [comment]
@DeepakPant I'm glad that error was finally fixed.

Regarding UpdateStatus, currently Twitter is not providing an implementation for dialogs which allow the user to edit the post, so SOOMLA is only providing the option to post on the user's behalf. If you want to show a dialog to edit, you must implement it by yourself.
Regarding a success event, you will get the `OnSocialActionFinished` (signup through `ProfileEvents`) event fired when the status is posted, so you can notify the user it posted a status for them.
Regarding privacy policy, I'm unsure if it breaks it or not, but the app should request permissions to post statuses on the user's behalf when they login, so the user should be aware that the application is going to do that. But as I said, I'm not a legal expert, so you should not take my word for it, and you are better off implementing a dialog to show the user.
 
Regarding the device's twitter account, currently our Android implementation for Twitter does not support this feature, but we might consider adding this in the future. On the other hand our iOS implementation for Twitter does support that. None of them supports authentication via the Twitter application.

Can I close this issue?

**Comment by DeepakPant** [comment]
Yes I am closing  myself ,Thank you
