### ISSUE TITLE
Command /usr/bin/codesign failed with exit code 1

### ISSUE THREAD

**Issue by robinDesBits** [soomla/unity3d-profile#9]
Hi ! I have a problem. When I compile on Xcode, I have this error : 

CodeSign /Users/xavier/Library/Developer/Xcode/DerivedData/Unity-iPhone-fpeszmwfkauotdedryaxpkpelaly/Build/Products/TouchOrDie.app/Frameworks/GoogleOpenSource.framework
    cd "/Users/xavier/Desktop/DELAMERDE/untitled folder 12/opiujk"
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    
Signing Identity:     "iPhone Developer: Xavier BERAUD (79ZUKS9QP2)"

    /usr/bin/codesign --force --sign E94204C8692B2240116F52F9147FF163E658C9D3 --preserve-metadata=identifier,entitlements,resource-rules /Users/xavier/Library/Developer/Xcode/DerivedData/Unity-iPhone-fpeszmwfkauotdedryaxpkpelaly/Build/Products/TouchOrDie.app/Frameworks/GoogleOpenSource.framework

Warning: usage of --preserve-metadata with option "resource-rules" (deprecated in Mac OS X >= 10.10)!
/Users/xavier/Library/Developer/Xcode/DerivedData/Unity-iPhone-fpeszmwfkauotdedryaxpkpelaly/Build/Products/TouchOrDie.app/Frameworks/GoogleOpenSource.framework: bundle format unrecognized, invalid, or unsuitable
Command /usr/bin/codesign failed with exit code 1

I tried a lot of things but I still can't figure this out... Couls you please help me ?!

Thank you.

**Comment by refaelos** [comment]
Is it really related to SOOMLA?

Sometime code-signing error occur when you don't have a valid signing key. Try to create a good signing key and work with that.

**Comment by sluzky** [comment]
@robinDesBits have you had any luck with this? was this resolved for you?

**Comment by robinDesBits** [comment]
Sorry, late answer. We solved all our problems by removing google + and twitter. Just Facebook is working fine, maybe we will try again later, but for now we have submitted our app without it.

**Comment by sluzky** [comment]
@robinDesBits a shame we couldn't help you to get this working.
So, are you going to try and use Twitter and Google+ soon?

**Comment by robinDesBits** [comment]
Don't worry, it's not a big deal, Facebook was the more important for us.
I don't know, we are waiting apple's validation, then I will probably work on it again.

**Comment by sluzky** [comment]
@robinDesBits ok, so should I leave the issue open? or will you create a new one if need be?

**Comment by refaelos** [comment]
Outdated issue. Closing. Open if still relevant.
